name: SoraStatistics
version: 1.0
main: me.manaki.plugin.sorastatistics.SoraStatistics
loadbefore:
  - Dungeons
depend:
  - PlaceholderAPI
  - PlayerData
softdepend:
  - Crafts
  - Dungeons
  - Farms
  - SantoryCore
  - Shops
  - SkyBattleClient
commands:
  sorastatistics:
    permission: sorastatistics.admin
    aliases:
      - sorastatistic
      - ss